### ISSUE TITLE
ComposerCLIの脆弱性対応

### ISSUE THREAD

**Issue by kin29** [quartetcom/static-analysis-kit#199]
[GHSA-7c6p-848j-wh5h](https://github.com/composer/composer/security/advisories/GHSA-7c6p-848j-wh5h)

**Comment by kin29** [comment]
@siketyan 
GitHub ActionとCircleCIにおいてcomposerを使用しているようですが、問題ないでしょうか？

**Comment by siketyan** [comment]
@kin29 

- CircleCI はこのリポジトリでは利用されていません
- GitHub Actions は利用されていますが， https://github.com/quartetcom/static-analysis-kit/actions/runs/7878023850/job/21495369318#step:3:12 を見るとわかる通り最新版がインストールされるようになっています．

**Comment by kin29** [comment]
@siketyan 
確認ありがとうございます！
https://github.com/quartetcom/static-analysis-kit/blob/8.2/.circleci/config.yml があったので利用しているのかと思っていました。
CircleCIを利用していないのであれば紛らわしいので.circleci/config.ymlの削除を検討しても良いかなと思いました。

**Comment by siketyan** [comment]
@kin29 .circleci/config.yml は自身のためではなくテンプレートとして存在していて，新規プロジェクトに static-analysis-kit を導入する際にワンタッチで CircleCI での静的検査をセットアップできるようにするためのものです．

**Comment by kin29** [comment]
@siketyan 
なるほど！そうだったんですね、失礼しました！
